// data.js - Chứa tất cả các đề thi IELTS Reading

const ieltsReadingTests = [
  {
    id: 1,
    title: "Practice Test 1: Smoking in China & Global Warming & Art & Antibiotics",
    passages: [
      {
        title: "Smoking Epidemic in China",
        text: `<p>A new study, conducted by scientists from Oxford University, the Chinese Academy of Medical Sciences and the Chinese Center for Disease Control, has warned that a third of all men currently under the age of 20 in China will eventually die prematurely if they do not give up smoking.</p>
        <p>The research, published in The Lancet medical journal, says two-thirds of men in China now start to smoke before 20. Around half of those men will die from the habit, it concludes.</p>
        <p>In 2010, around one million people in China died from tobacco usage. But researchers say that if current trends continue, that will double to two million people - mostly men - dying every year by 2030, making it a "growing epidemic of premature death".</p>
        <p>But co-author Richard Peto said there was hope - if people can be persuaded to quit. "The key to avoid this huge wave of deaths is cessation, and if you are a young man, don't start," he said.</p>
        <p>In many parts of China, meals often fit a comfortable pattern. After putting down their chopsticks, men commonly push their chairs back from the table and light cigarettes. No wonder China has struggled to impose a smoking ban in public places. Here, relationships are often built amid clouds of smoke.</p>
        <p>Expensive brands of cigarettes, often decorated with gold detailing on the cartons, are given as gifts. And ordinary brands are affordable to all but the very poor, costing just 2.5 yuan ($0.4; £0.25) a pack.</p>
        <p>In a country where smoking is so ingrained in daily life, few understand the harmful effects of tobacco use. According to the World Health Organization (WHO), only 25% of Chinese adults can list the specific health hazards of smoking, from lung cancer to heart disease.</p>
        <p>Perhaps it should come as no surprise, then, that only 10% of Chinese smokers quit by choice. Instead, most are forced to give up their cigarettes because they're too sick to continue.</p>
        <p>While smoking rates have fallen in developed countries - to less than one in five in the US - they have risen in China, as cigarettes have become more available and consumers richer.</p>
        <p>Authorities have shown concern over the rise, with Beijing even introducing a public smoking ban. But efforts have been hampered by the habit's popularity, and its usefulness as a source of tax - the government collects about 428 billion yuan (£44billion, $67billion) in tobacco taxes each year. Globally, tobacco kills up to half of its users, according to the World Health Organization.</p>`,
        questions: [
          { no: 1, type: "mc", question: "How many Chinese men start to smoke before the age of 20?", options: ["A. one-third", "B. two-thirds", "C. half", "D. all of them"], answer: "B. two-thirds" },
          { no: 2, type: "mc", question: "What does the word “those men” in paragraph 2 refer to?", options: ["A. Men who smoke under the age of 20", "B. Men who smoke above the age of 20", "C. Men who give up smoking", "D. Men who smoke in public"], answer: "A. Men who smoke under the age of 20" },
          { no: 3, type: "mc", question: "By 2030, how many men in China may die from smoking every year?", options: ["A. one million", "B. two million", "C. three million", "D. four million"], answer: "B. two million" },
          { no: 4, type: "mc", question: "In many areas of China, when do men usually smoke?", options: ["A. Before a meal", "B. After a meal", "C. Before they go to sleep", "D. When they get up"], answer: "B. After a meal" },
          { no: 5, type: "mc", question: "According to WHO, only ______ of Chinese adults can list bad effects of smoking.", options: ["A. one-third", "B. one-fourth", "C. one-fifth", "D. a half"], answer: "B. one-fourth" },
          { no: 6, type: "mc", question: "“Beijing” refers to ______. ", options: ["A. China", "B. The city of Beijing", "C. The Chinese government", "D. People who live in Beijing"], answer: "C. The Chinese government" },
          { no: 7, type: "mc", question: "What is Richard Peto's attitude toward smoking in China?", options: ["A. He doesn't believe that people will give up smoking", "B. He is disappointed with the Chinese government.", "C. He thinks that people possibly stop smoking if they see reasons.", "D. He is sure about the rise of future deaths in China."], answer: "C. He thinks that people possibly stop smoking if they see reasons." },
          { no: 8, type: "mc", question: "Which of the following words does the word “hamper” have closest meaning to?", options: ["A. basket", "B. assist", "C. prohibit", "D. restrict"], answer: "D. restrict" },
          { no: 9, type: "mc", question: "What is the writer's purpose?", options: ["A. To argue over smoking policy in China", "B. To support smoking in China", "C. To warn and prevent smoking in China", "D. To report the result of a research paper"], answer: "C. To warn and prevent smoking in China" },
          { no: 10, type: "mc", question: "What does the writer imply about Chinese government?", options: ["A. They do not want to stop people from smoking.", "B. They have tried to stop people from smoking in public but with little success.", "C. They have tried to close tobacco companies.", "D. They do not care about smoking."], answer: "B. They have tried to stop people from smoking in public but with little success." }
        ]
      },
      {
        title: "Solutions to Global Warming",
        text: `<p>The evidence that humans are causing global warming is strong, but the question of what to do about it remains controversial. Economics, sociology, and politics are all important factors in planning for the future.</p>
        <p>Even if we stopped emitting greenhouse gases (GHGs) today, the Earth would still warm by another degree Fahrenheit or so. But what we do from today forward makes a big difference. Depending on our choices, scientists predict that the Earth could eventually warm by as little as 2.5 degrees or as much as 10 degrees Fahrenheit.</p>
        <p>A commonly cited goal is to stabilize GHG concentrations around 450-550 parts per million (ppm), or about twice pre-industrial levels. This is the point at which many believe the most damaging impacts of climate change can be avoided. Current concentrations are about 380 ppm, which means there isn't much time to lose. According to the IPCC, we'd have to reduce GHG emissions by 50% to 80% of what they're on track to be in the next century to reach this level.</p>
        <p>Is this possible?</p>
        <p>Many people and governments are already working hard to cut greenhouse gases, and everyone can help.</p>
        <p>Researchers Stephen Pacala and Robert Socolow at Princeton University have suggested one approach that they call "stabilization wedges." This means reducing GHG emissions from a variety of sources with technologies available in the next few decades, rather than relying on an enormous change in a single area. They suggest 7 wedges that could each reduce emissions, and all of them together could hold emissions at approximately current levels for the next 50 years, putting us on a path to stabilize around 500 ppm.</p>
        <p>There are many possible wedges, including improvements to energy efficiency and vehicle fuel economy (so less energy has to be produced), and increases in wind and solar power, hydrogen produced from renewable sources, biofuels (produced from crops), natural gas, and nuclear power. There is also the potential to capture the carbon dioxide emitted from fossil fuels and store it underground—a process called "carbon sequestration."</p>
        <p>In addition to reducing the gases we emit to the atmosphere, we can also increase the amount of gases we take out of the atmosphere. Plants and trees absorb CO2 as they grow, "sequestering" carbon naturally. Increasing forestlands and making changes to the way we farm could increase the amount of carbon we're storing.</p>
        <p>Some of these technologies have drawbacks, and different communities will make different decisions about how to power their lives, but the good news is that there are a variety of options to put us on a path toward a stable climate.</p>`,
        questions: [
          { no: 11, type: "mc", question: "The word \"we\" in paragraph 2 refers to ............", options: ["A. humans", "B. economists, sociologists, and politicians", "C. animals", "D. scientists"], answer: "A. humans" },
          { no: 12, type: "mc", question: "According to paragraph 2, how many degrees could the Earth warm up?", options: ["A. 2.5", "B. 2.5 or 10", "C. 10", "D. from 2.5 to 10"], answer: "D. from 2.5 to 10" },
          { no: 13, type: "mc", question: "According to paragraph 3, why should we stabilize GHG concentrations around 450-550 parts per million?", options: ["A. to avoid the most serious effects of climate change", "B. to avoid all damaging impacts of climate change", "C. to mend the most damaging impacts of climate change", "D. to stop climate change"], answer: "A. to avoid the most serious effects of climate change" },
          { no: 14, type: "mc", question: "What does “which” in paragraph 3 refer to?", options: ["A. current concentrations", "B. that current concentrations are about 380 ppm", "C. 380 ppm", "D. ppm"], answer: "B. that current concentrations are about 380 ppm" },
          { no: 15, type: "mc", question: "Why does the author mention Stephen Pacala and Robert Socolow?", options: ["A. To introduce two researchers in the field", "B. To prove that researchers are working to reduce GHG emission", "C. To introduce one way to reduce GHG emission", "D. To introduce Princeton University"], answer: "C. To introduce one way to reduce GHG emission" },
          { no: 16, type: "mc", question: "What stabilization wedges are NOT mentioned in the passage?", options: ["A. create environment-friendly materials", "B. capture and store carbon dioxide underground", "C. increase the use of renewable energy", "D. grow more trees"], answer: "A. create environment-friendly materials" },
          { no: 17, type: "mc", question: "What does “them” refer to?", options: ["A. researchers", "B. humans", "C. renewable resources", "D. wedges"], answer: "D. wedges" },
          { no: 18, type: "mc", question: "What is the best title for this passage?", options: ["A. Arguments over Global Warming", "B. Global Warming and its Causes", "C. Global Warming Solutions", "D. Global Warming's Effect on Earth"], answer: "C. Global Warming Solutions" },
          { no: 19, type: "mc", question: "“Sequestering” has closest meaning to .........", options: ["A. absorb", "B. isolate", "C. release", "D. emit"], answer: "A. absorb" },
          { no: 20, type: "mc", question: "Why does the writer mention “drawbacks” in the last paragraph?", options: ["A. To introduce the disadvantages of solutions in the following paragraph", "B. To emphasize the disadvantages of the solutions in the previous paragraph", "C. To recommend readers not to use the solutions", "D. To emphasize the advantages of the solutions in different contexts"], answer: "B. To emphasize the disadvantages of the solutions in the previous paragraph" }
        ]
      },
      {
        title: "Appreciating Works of Art",
        text: `<p>Art communicates to us primarily through our eyes. We look at art, and we try to find some meaning in the experience. If we are to begin to think about art more seriously, we might do well to become more aware of the process of seeing itself.</p>
        <p>Science tells us that seeing is a mode of perception, or the recognition and interpretation of sensory data-in other words, how information comes in our senses, and what we make of it. In visual perception our eyes take in information in the form of light patterns; the brain processes these patterns to give them meaning. The mechanics of perception work much the same way for everyone, yet in a given situation we do not all see the same things.</p>
        <p>We can take great pleasure in merely looking at art, just as we take pleasure in the view of a distant mountain range or watching the sun set over the ocean. But art, unlike nature, is a human creation. It is one of the many ways we express ourselves and attempt to communicate. A work of art is the product of human intelligence, and we can meet it with our own intelligence on equal footing. This is where study comes in.</p>
        <p>The understanding of process - the how - often contributes quite a lot to our appreciation of art. If you understand why painting in watercolor may be different from painting in oil, why clay responds differently to the artist's hands than does wood or glass - you will have a richer appreciation of the artist's expression.</p>
        <p>Knowing the place of a work of art in history - what went before and came after - can also deepen your understanding. Artists learn to make art by studying the achievements of the past and observing the efforts of their contemporaries. They adapt ideas to serve their own needs and then bequeath those ideas to future generations of artists. For example, Matisse assumed that his audience would know that Venus was the ancient Roman goddess of love. But he also hoped that they would be familiar with one Venus in particular, a famous Greek statue known as the Venus de Milo.</p>
        <p>An artist may create a specific work for any of a thousand reasons. An awareness of the why may give some insight as well. Looking at Van Gogh's <em>The Starry Night</em>, it might help you know that Van Gogh was intrigued by the belief that people journeyed to a star after their death, and that there they continued their lives. "Just as we take the train to get to Tarascon or Rouen," he wrote in a letter, "we take death to reach a star." This knowledge might help you understand why Van Gogh felt so strongly about the night sky, and what his painting might have meant to him.</p>
        <p>But no matter how much you study, Van Gogh's painting will never mean for you exactly what it meant for him, nor should it. Great works of art hold many meanings. The greatest of them seem to speak anew to each generation and to each attentive observer. The most important thing is that they mean something for you, that your own experiences, thoughts, and emotions find a place in them.</p>`,
        questions: [
          { no: 21, type: "mc", question: "According to paragraph 2, the process of visual perception ............", options: ["A. is not the same for all people", "B. begins with patterns of light", "C. is not very scientific", "D. requires other senses to function"], answer: "B. begins with patterns of light" },
          { no: 22, type: "mc", question: "What did Matisse reinterpret?", options: ["A. A goddess from mythology", "B. A painting by another artist", "C. An ancient sculpture", "D. A man in history"], answer: "C. An ancient sculpture" },
          { no: 23, type: "mc", question: "The word \"them\" in the last paragraph refers to ............", options: ["A. each attentive observer", "B. thoughts and emotions", "C. a lifetime of experiences", "D. great works of art"], answer: "D. great works of art" },
          { no: 24, type: "mc", question: "The word \"bequeath\" in the passage is closest in meaning to ............", options: ["A. make out", "B. pass on", "C. look over", "D. take in"], answer: "B. pass on" },
          { no: 25, type: "mc", question: "The author mentions all of the following ways to enhance the appreciation of art EXCEPT ........", options: ["A. understanding the artistic process", "B. becoming familiar with the history", "C. experiencing the art by copying", "D. knowing about the life of the artist"], answer: "C. experiencing the art by copying" },
          { no: 26, type: "mc", question: "What is the main topic of this passage?", options: ["A. Visual perception of sensory material", "B. The historical context for artistic expression", "C. Studying Van Gogh's The Starry Night", "D. The appreciation of works of art"], answer: "D. The appreciation of works of art" },
          { no: 27, type: "mc", question: "Which of the sentences below best expresses the information in the highlighted statement in the passage?", options: ["A. We see images differently because of the mode of perception.", "B. Although we see images differently, the mode of perception is similar.", "C. Since the mode of perception is similar, we see images in the same way.", "D. When the mode of perception is the same, we see the same images"], answer: "B. Although we see images differently, the mode of perception is similar." },
          { no: 28, type: "mc", question: "Why might Van Gogh have painted The Starry Night?", options: ["A. To symbolize the journey of life after death", "B. To create a dramatic contrast with the sky", "C. To place a strong image in the foreground", "D. To include nature from his early experience"], answer: "A. To symbolize the journey of life after death" },
          { no: 29, type: "mc", question: "The word \"intrigued\" in the passage is closest in meaning to ............", options: ["A. very pleased", "B. very confused", "C. very interested", "D. very surprised"], answer: "C. very interested" },
          { no: 30, type: "mc", question: "What can be inferred from the last paragraph?", options: ["A. Greatest artworks are impossible to understand.", "B. The author shows negative feelings toward contemporary art.", "C. People need knowledge to understand art.", "D. What we see in art is determined by our emotions, experiences, and thoughts."], answer: "D. What we see in art is determined by our emotions, experiences, and thoughts." }
        ]
      },
      {
        title: "Antibiotic Resistance",
        text: `<p>Antibiotics block the life cycle of bacteria that invade the human body. The first of these antibiotics, penicillin, works by blocking the molecules that construct the cell walls of particular bacteria. The bacteria, with incomplete cell walls, are not able to reproduce.</p>
        <p>When penicillin was introduced during World War II, it was truly a "miracle drug." Until that time, anyone who was cut or wounded stood a great risk of infection. Once penicillin became available, the situation changed. Wounded soldiers, children with ear infections, and many others began to benefit from the ability to block the growth of bacteria.</p>
        <p>While humanity may have won that particular battle against bacteria, the war is far from over. The reason is that in any bacterial population, there are bound to be a few bacteria that, for one reason or another, are not affected by a particular antibiotic. For example, they may have a slightly differently shaped enzyme that builds cell walls, so that penicillin will not fit onto that particular shape of the enzyme. These bacteria will not be affected by that particular drug.</p>
        <p>For that small group, the antibiotic is a real godsend. It doesn't affect them, but it does wipe out all of their competition. They are thus free to multiply, and, over time, all of the bacteria will have whatever properties that made those individuals resistant.</p>
        <p>Traditionally, medical scientists have dealt with this phenomenon by developing a large number of antibiotics, each of which intervenes in the bacterial life cycle in a slightly different way.</p>
        <p>Consequently, if you happen to have a bacterium that is resistant to one antibiotic, probably it will succumb to the action of another. You may, in fact, have had the experience of going to a doctor with an infection, being given an antibiotic, and then finding that it didn't work. In all likelihood, all your doctor had to do then was prescribe a different antibiotic and everything was fine.</p>
        <p>The problem is that as time has passed, more and more bacteria have become resistant to antibiotics. In fact, currently, there is one strain of bacteria- Staphylococcus-that is resistant to every commercially available antibiotic except one, and in 1996, a bacterium with lowered resistance to that last antibiotic appeared in Japan.</p>
        <p>The appearance of drug-resistant bacteria is not particularly surprising; in fact, it probably should have been anticipated. Nevertheless, in the late 1980s, there was a general sense of complacency among scientists on the antibiotic question. Little profit was to be made by developing the one-hundred-and-first antibiotic. Drug companies concentrated their efforts on other areas. Therefore, a gap developed between the production of new antibiotics and the development of resistance among bacteria.</p>
        <p>By the early 1990s, this gap was recognized and highlighted in several national news magazines. More companies returned to develop new kinds of antibiotics, and currently, a number are undergoing clinical trials. By early in the twenty-first century, some of these new drugs will start to come on the market, and the problem will be "solved," at least for the moment.</p>
        <p>Additional research will focus on the processes by which cells repair the constant damage to DNA, but the computer design of new drugs, the development of new antibiotics, and techniques to combat bacteria should remain a top priority.</p>`,
        questions: [
          { no: 31, type: "mc", question: "How do antibiotics treat infections?", options: ["A. They interfere with the reproductive cycle of bacteria.", "B. They construct cell walls to resist bacteria.", "C. They inject enzymes that explode in affected cells.", "D. They increase the mitosis of healthy cells"], answer: "A. They interfere with the reproductive cycle of bacteria." },
          { no: 32, type: "mc", question: "The word \"them\" in paragraph 4 refers to ............", options: ["A. whatever properties", "B. resistant bacteria", "C. their competition", "D. those individuals"], answer: "D. those individuals" },
          { no: 33, type: "mc", question: "The word \"anticipated\" in the passage is closest in meaning to ........", options: ["A. predicted", "B. concealed", "C. investigated", "D. disregarded"], answer: "A. predicted" },
          { no: 34, type: "mc", question: "Which of the following best expresses the main idea of this passage?", options: ["A. The \"miracle drug\" penicillin", "B. Drug-resistant bacteria", "C. Staphylococcus infections", "D. Gene therapy treatments"], answer: "B. Drug-resistant bacteria" },
          { no: 35, type: "mc", question: "According to paragraph 4, why do some bacteria benefit from antibiotics?", options: ["A. The antibiotic eliminates competing bacteria, allowing resistant bacteria to reproduce.", "B. The resistant bacteria compete with the antibiotic, and the bacteria become stronger.", "C. The competition helps the resistant bacteria to multiply by reproducing with the resistant type.", "D. The properties of the antibiotic are acquired by the bacteria, making it resistant to the competition."], answer: "A. The antibiotic eliminates competing bacteria, allowing resistant bacteria to reproduce." },
          { no: 36, type: "mc", question: "The word \"complacency\" in the passage is closest in meaning to ......", options: ["A. consensus of agreement", "B. fear of consequences", "C. lack of concern", "D. awareness of potential"], answer: "C. lack of concern" },
          { no: 37, type: "mc", question: "Which of the sentences below best expresses the information in the highlighted statement in the passage?", options: ["A. Some antibiotics affect a population of bacteria more efficiently than others.", "B. There are several reasons why some bacteria do not respond to most antibiotics.", "C. The effect of antibiotics on bacteria is to bind them together into one population.", "D. A small number of bacteria in any sample will probably be resistant to a specific antibiotic."], answer: "D. A small number of bacteria in any sample will probably be resistant to a specific antibiotic." },
          { no: 38, type: "mc", question: "The author mentions all of the following reasons for drug resistant bacteria to appear EXCEPT......", options: ["A. there was not enough profit incentive for companies to continue developing new antibiotics.", "B. statistically, some drug-resistant bacteria will occur naturally in any large population of bacteria", "C. the newer antibiotics were not as strong and effective as the original penicillin-based drugs", "D. competing bacteria are destroyed by antibiotics, allowing resistant bacteria to prosper."], answer: "C. the newer antibiotics were not as strong and effective as the original penicillin-based drugs" },
          { no: 39, type: "mc", question: "It can be inferred from the passage that ......", options: ["A. research to develop new antibiotics will not be necessary in the future", "B. the scientific community was not surprised by the resistant strains of bacteria", "C. antibiotics are not very expensive when they are made available commercially", "D. it takes years for a new drug to be made available commercially for consumers"], answer: "D. it takes years for a new drug to be made available commercially for consumers" },
          { no: 40, type: "mc", question: "Which of the following statements is NOT a main idea of the passage?", options: ["A. Many strains of bacteria have become resistant to the antibiotics currently available.", "B. Funding for the production of new antibiotics has been allocated to drug companies.", "C. The first antibiotics were very effective in blocking the reproduction of bacteria.", "D. New antibiotics are being developed to combat bacteria that resist the older antibiotics."], answer: "B. Funding for the production of new antibiotics has been allocated to drug companies." }
        ]
      }
    ]
  }

  // Bạn có thể thêm các đề khác (Test 2, Test 3, ...) vào đây, cùng cấu trúc như trên
];